name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - name: Grant execute permisions for gradlew
        run: chmod +x gradlew
      - name: Build Artifacts
        run: ./gradlew build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v1
        with:
            name: build-artifact
            path: build/libs
